export const USER_ROLES = {
  MASTER_ADMIN: 'MASTER_ADMIN',
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  CEO: 'CEO',
  UNDERWRITING_ADMIN: 'UNDERWRITING_ADMIN',
  UNDERWRITING_OFFICER: 'UNDERWRITING_OFFICER',
  UNDERWRITING_OFFICER_I: 'UNDERWRITING_OFFICER_I',
  UNDERWRITING_OFFICER_II: 'UNDERWRITING_OFFICER_II',
  SENIOR_UNDERWRITING_OFFICER: 'SENIOR_UNDERWRITING_OFFICER',
  SUPERVISOR_UNDERWRITING: 'SUPERVISOR_UNDERWRITING',
  MANAGER_UNDERWRITING: 'MANAGER_UNDERWRITING',
  HEAD_UNDERWRITING: 'HEAD_UNDERWRITING',
  CLAIMS_ADMIN: 'CLAIMS_ADMIN',
  CLAIM_OFFICER: 'CLAIM_OFFICER',
  CLAIM_OFFICER_I: 'CLAIM_OFFICER_I',
  CLAIM_OFFICER_II: 'CLAIM_OFFICER_II',
  SENIOR_CLAIM_OFFICER: 'SENIOR_CLAIM_OFFICER',
  SUPERVISOR_CLAIMS: 'SUPERVISOR_CLAIMS',
  MANAGER_CLAIMS: 'MANAGER_CLAIMS',
  HEAD_CLAIMS: 'HEAD_CLAIMS',
  CUSTOMER_ADMIN: 'CUSTOMER_ADMIN',
  CUSTOMER: 'CUSTOMER',
  GUEST: 'GUEST',
} as const;

export const CLAIM_STATUS = {
  SUBMITTED: 'submitted',
  UNDER_REVIEW: 'under_review',
  APPROVED: 'approved',
  REJECTED: 'rejected',
  PAID: 'paid',
} as const;

export const POLICY_STATUS = {
  ACTIVE: 'active',
  PENDING: 'pending',
  EXPIRED: 'expired',
  CANCELLED: 'cancelled',
  REJECTED: 'rejected',
} as const;

export const PAYMENT_STATUS = {
  PENDING: 'pending',
  SUCCESS: 'success',
  FAILED: 'failed',
  REFUNDED: 'refunded',
} as const;